# Generated by Django 6.0.4 on 2026-04-09 00:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Daily rate for full-day projects', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='rate_per_square_meter',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per square meter for flooring, painting, etc.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
