# Generated by Django 4.2.7 on 2026-04-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_phone_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per hour in local currency', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='id_passport_number',
            field=models.CharField(blank=True, help_text='ID or Passport number for verification', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio_description',
            field=models.TextField(blank=True, help_text='Description of portfolio and past work'),
        ),
        migrations.AddField(
            model_name='user',
            name='references',
            field=models.TextField(blank=True, help_text='Professional references and testimonials'),
        ),
        migrations.AddField(
            model_name='user',
            name='service_categories',
            field=models.CharField(blank=True, help_text='Comma-separated list of service categories', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, help_text='List of professional skills and qualifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='square_meter_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per square meter for construction services', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp contact number', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, help_text='Years of professional experience', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
