# Generated by Django 6.0.4 on 2026-04-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_portfolio_image_portfolioimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per day in local currency', max_digits=10, null=True),
        ),
    ]
