# Generated by Django 6.0.4 on 2026-04-11 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_daily_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Account name/label', max_length=100)),
                ('bank', models.CharField(choices=[('standard_bank', 'Standard Bank'), ('fnb', 'First National Bank (FNB)'), ('absa', 'Absa Bank'), ('nedbank', 'Nedbank'), ('capitec', 'Capitec Bank'), ('investec', 'Investec'), ('african_bank', 'African Bank'), ('tymebank', 'TymeBank'), ('other', 'Other')], help_text='Bank name', max_length=20)),
                ('other_bank_name', models.CharField(blank=True, help_text="Specify if 'Other' bank selected", max_length=100)),
                ('account_holder_name', models.CharField(help_text='Full name of account holder', max_length=100)),
                ('account_number', models.CharField(help_text='Bank account number', max_length=20)),
                ('branch_code', models.CharField(help_text='6-digit branch code', max_length=10)),
                ('account_type', models.CharField(choices=[('cheque', 'Cheque Account'), ('savings', 'Savings Account'), ('transmission', 'Transmission Account'), ('credit_card', 'Credit Card Account'), ('business', 'Business Account')], default='cheque', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this account is active for payments')),
                ('is_default', models.BooleanField(default=False, help_text='Default account for EFT payments')),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum payment amount', max_digits=10)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum payment amount (leave blank for unlimited)', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this account')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=200)),
                ('description', models.TextField(help_text='Template description')),
                ('category', models.CharField(choices=[('payment', 'Payment Settings'), ('banking', 'Banking Information'), ('whatsapp', 'WhatsApp Configuration'), ('email', 'Email Configuration'), ('sms', 'SMS Configuration'), ('platform', 'Platform Settings'), ('fees', 'Fee Structure'), ('api', 'API Keys & Credentials'), ('ui', 'User Interface'), ('notifications', 'Notification Settings'), ('security', 'Security Settings'), ('integrations', 'Third-party Integrations')], max_length=20)),
                ('configurations', models.JSONField(help_text='Template configurations as JSON')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuration Template',
                'verbose_name_plural': 'Configuration Templates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_type', models.CharField(choices=[('smtp', 'SMTP Settings'), ('sendgrid', 'SendGrid Settings'), ('ses', 'AWS SES Settings'), ('mailgun', 'Mailgun Settings')], max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='Whether this email configuration is active')),
                ('host', models.CharField(blank=True, help_text='SMTP host', max_length=255)),
                ('port', models.PositiveIntegerField(blank=True, help_text='SMTP port', null=True)),
                ('username', models.CharField(blank=True, help_text='SMTP username', max_length=255)),
                ('password', models.CharField(blank=True, help_text='SMTP password', max_length=255)),
                ('use_tls', models.BooleanField(default=True, help_text='Use TLS encryption')),
                ('use_ssl', models.BooleanField(default=False, help_text='Use SSL encryption')),
                ('from_email', models.EmailField(help_text='Default from email address', max_length=254)),
                ('from_name', models.CharField(help_text='Default from name', max_length=100)),
                ('api_key', models.CharField(blank=True, help_text='API key for service-based email providers', max_length=255)),
                ('domain', models.CharField(blank=True, help_text='Domain for service-based email providers', max_length=255)),
                ('daily_limit', models.PositiveIntegerField(default=1000, help_text='Daily email sending limit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configurations',
                'ordering': ['-is_active', 'config_type'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('yoco', 'Yoco (Mobile Card Payments)'), ('ozow', 'Ozow (Instant EFT)'), ('eft', 'EFT Transfer'), ('in_person', 'In-Person Payment')], max_length=20, unique=True)),
                ('name', models.CharField(help_text='Display name for this payment method', max_length=100)),
                ('description', models.TextField(help_text='Description shown to users')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this payment method is available')),
                ('icon_class', models.CharField(help_text="Font Awesome icon class (e.g., 'fas fa-credit-card')", max_length=50)),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Transaction fee percentage', max_digits=5)),
                ('fee_fixed', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed transaction fee', max_digits=10)),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum payment amount', max_digits=10)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum payment amount', max_digits=10, null=True)),
                ('processing_time', models.CharField(default='Instant', help_text='Expected processing time', max_length=50)),
                ('instructions', models.TextField(blank=True, help_text='Special instructions for this payment method')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('commission', 'Commission Fee'), ('service_fee', 'Service Fee'), ('transaction_fee', 'Transaction Fee'), ('withdrawal_fee', 'Withdrawal Fee')], max_length=20, unique=True)),
                ('name', models.CharField(help_text='Display name for this fee', max_length=100)),
                ('description', models.TextField(help_text='Description of what this fee covers')),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee percentage', max_digits=5)),
                ('fee_fixed', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed fee amount', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this fee is currently active')),
                ('applies_to', models.CharField(help_text="Who this fee applies to (e.g., 'service_provider', 'homeowner', 'both')", max_length=50)),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum amount for fee to apply', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Fee',
                'verbose_name_plural': 'Platform Fees',
                'ordering': ['fee_type'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Configuration key', max_length=100, unique=True)),
                ('value', models.TextField(help_text='Configuration value (JSON for complex data)')),
                ('config_type', models.CharField(choices=[('payment', 'Payment Settings'), ('email', 'Email Settings'), ('platform', 'Platform Settings'), ('whatsapp', 'WhatsApp Settings'), ('fees', 'Fee Settings'), ('banking', 'Banking Settings')], default='platform', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of this configuration')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
                'ordering': ['config_type', 'key'],
            },
        ),
        migrations.CreateModel(
            name='DynamicConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique configuration key', max_length=100, unique=True)),
                ('category', models.CharField(choices=[('payment', 'Payment Settings'), ('banking', 'Banking Information'), ('whatsapp', 'WhatsApp Configuration'), ('email', 'Email Configuration'), ('sms', 'SMS Configuration'), ('platform', 'Platform Settings'), ('fees', 'Fee Structure'), ('api', 'API Keys & Credentials'), ('ui', 'User Interface'), ('notifications', 'Notification Settings'), ('security', 'Security Settings'), ('integrations', 'Third-party Integrations')], help_text='Configuration category', max_length=20)),
                ('data_type', models.CharField(choices=[('string', 'Text String'), ('integer', 'Integer Number'), ('decimal', 'Decimal Number'), ('boolean', 'True/False'), ('json', 'JSON Object'), ('list', 'List of Values'), ('encrypted', 'Encrypted Data'), ('url', 'URL Address'), ('email', 'Email Address'), ('phone', 'Phone Number'), ('file_path', 'File Path'), ('html', 'HTML Content'), ('css', 'CSS Styles'), ('javascript', 'JavaScript Code')], default='string', help_text='Type of data stored', max_length=20)),
                ('value', models.TextField(help_text='Configuration value (encrypted for sensitive data)')),
                ('encrypted_value', models.TextField(blank=True, help_text='Encrypted sensitive data', null=True)),
                ('name', models.CharField(help_text='Human-readable name', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of this configuration')),
                ('is_required', models.BooleanField(default=False, help_text='Whether this configuration is required')),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='Validation rules as JSON')),
                ('default_value', models.TextField(blank=True, help_text='Default value if not set')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this config is accessible to all users')),
                ('is_editable', models.BooleanField(default=True, help_text='Whether this config can be edited')),
                ('requires_restart', models.BooleanField(default=False, help_text='Whether app restart is needed after change')),
                ('version', models.PositiveIntegerField(default=1, help_text='Configuration version')),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dynamic Configuration',
                'verbose_name_plural': 'Dynamic Configurations',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.TextField(blank=True, help_text='Previous value')),
                ('new_value', models.TextField(blank=True, help_text='New value')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.TextField(blank=True, help_text='Reason for the change')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.dynamicconfiguration')),
            ],
            options={
                'verbose_name': 'Configuration History',
                'verbose_name_plural': 'Configuration Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dynamicconfiguration',
            index=models.Index(fields=['category', 'key'], name='core_dynami_categor_37f19f_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicconfiguration',
            index=models.Index(fields=['is_active', 'category'], name='core_dynami_is_acti_df1c60_idx'),
        ),
        migrations.AddIndex(
            model_name='configurationhistory',
            index=models.Index(fields=['configuration', '-changed_at'], name='core_config_configu_661f69_idx'),
        ),
        migrations.AddIndex(
            model_name='configurationhistory',
            index=models.Index(fields=['changed_by', '-changed_at'], name='core_config_changed_cec473_idx'),
        ),
    ]
