# Generated by Django 6.0.4 on 2026-04-11 12:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bankaccount_configurationtemplate_emailconfiguration_and_more'),
        ('orders', '0007_bankdetails_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyServiceFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(help_text='Month for which fee is charged')),
                ('base_fee', models.DecimalField(decimal_places=2, help_text='Base monthly service fee', max_digits=10)),
                ('additional_fees', models.DecimalField(decimal_places=2, default=0.0, help_text='Additional fees for the month', max_digits=10)),
                ('total_fee', models.DecimalField(decimal_places=2, help_text='Total fee for the month', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('charged', 'Charged'), ('paid', 'Paid'), ('waived', 'Waived'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid towards this fee', max_digits=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about this monthly fee')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(limit_choices_to={'user_type': 'service_provider'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Service Fee',
                'verbose_name_plural': 'Monthly Service Fees',
                'ordering': ['-month'],
                'unique_together': {('provider', 'month')},
            },
        ),
        migrations.CreateModel(
            name='ProviderEarnings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('earning_type', models.CharField(choices=[('job_completion', 'Job Completion'), ('milestone', 'Milestone Payment'), ('bonus', 'Bonus Payment'), ('adjustment', 'Manual Adjustment')], default='job_completion', max_length=20)),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Total amount before deductions', max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Platform commission deducted', max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Amount after commission deduction', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('available', 'Available for Withdrawal'), ('processing', 'Processing Payment'), ('paid', 'Paid'), ('frozen', 'Frozen - Under Review')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of the earning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_at', models.DateTimeField(blank=True, help_text='When earning becomes available for withdrawal', null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('provider', models.ForeignKey(limit_choices_to={'user_type': 'service_provider'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider Earning',
                'verbose_name_plural': 'Provider Earnings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Total gross amount before fees', max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Platform service fee', max_digits=10)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Processing fee for urgent payments', max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Final amount to be paid', max_digits=10)),
                ('payout_method', models.CharField(choices=[('ewallet', 'E-Wallet'), ('cash_send', 'Cash Send'), ('payshap', 'PayShap'), ('bank_transfer', 'Bank Transfer'), ('instant_payment', 'Instant Payment'), ('manual', 'Manual Payment')], max_length=20)),
                ('priority', models.CharField(choices=[('standard', 'Standard (2 days)'), ('urgent', 'Urgent (Immediate)'), ('express', 'Express (Same day)')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Payment Requested'), ('processing', 'Processing'), ('approved', 'Approved'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('recipient_name', models.CharField(help_text='Full name of recipient', max_length=100)),
                ('recipient_phone', models.CharField(blank=True, help_text='Phone number for mobile payments', max_length=20)),
                ('recipient_email', models.CharField(blank=True, help_text='Email for e-wallet payments', max_length=100)),
                ('bank_account', models.CharField(blank=True, help_text='Bank account number', max_length=100)),
                ('bank_name', models.CharField(blank=True, help_text='Bank name', max_length=100)),
                ('branch_code', models.CharField(blank=True, help_text='Bank branch code', max_length=20)),
                ('reference_number', models.CharField(help_text='Unique reference for this payout', max_length=50, unique=True)),
                ('transaction_id', models.CharField(blank=True, help_text='External transaction ID', max_length=100)),
                ('receipt_url', models.URLField(blank=True, help_text='URL to payment receipt')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Provider notes for this payout')),
                ('admin_notes', models.TextField(blank=True, help_text='Admin internal notes')),
                ('earnings', models.ManyToManyField(help_text='Earnings included in this payout', to='core.providerearnings')),
                ('provider', models.ForeignKey(limit_choices_to={'user_type': 'service_provider'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider Payout',
                'verbose_name_plural': 'Provider Payouts',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('earning', 'Earning Credit'), ('payout', 'Payout Debit'), ('fee', 'Fee Charge'), ('refund', 'Refund'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('description', models.TextField(help_text='Transaction description')),
                ('reference_number', models.CharField(blank=True, help_text='Reference number for this transaction', max_length=50)),
                ('external_transaction_id', models.CharField(blank=True, help_text='External system transaction ID', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('monthly_fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.monthlyservicefee')),
                ('provider', models.ForeignKey(limit_choices_to={'user_type': 'service_provider'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('earning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.providerearnings')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.providerpayout')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
