# Generated by Django 6.0.4 on 2026-04-11 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_monthlyservicefee_providerearnings_providerpayout_and_more'),
        ('orders', '0007_bankdetails_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('eft', 'EFT Transfer'), ('ozow', 'Ozow Payment'), ('cash', 'Cash Payment'), ('card', 'Card Payment'), ('other', 'Other Method')], default='eft', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_reference', models.CharField(blank=True, help_text='Bank reference or transaction ID', max_length=100)),
                ('receipt_number', models.CharField(help_text='Unique receipt number', max_length=50, unique=True)),
                ('bank_name', models.CharField(blank=True, help_text='Bank name for EFT payments', max_length=100)),
                ('account_holder', models.CharField(blank=True, help_text='Account holder name', max_length=100)),
                ('payment_date', models.DateTimeField(help_text='Date payment was made or confirmed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When payment was confirmed', null=True)),
                ('description', models.TextField(blank=True, help_text='Payment description or notes')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('homeowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment Receipt',
                'verbose_name_plural': 'Payment Receipts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('homeowner_payment', 'Homeowner Payment'), ('provider_payout', 'Provider Payout'), ('platform_fee', 'Platform Fee'), ('commission', 'Commission'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('homeowner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('payment_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_transactions', to='core.paymentreceipt')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['homeowner', '-created_at'], name='core_paymen_homeown_a89769_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['payment_method', '-created_at'], name='core_paymen_payment_11679c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['payment_status', '-created_at'], name='core_paymen_payment_ced293_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['receipt_number'], name='core_paymen_receipt_628e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='receipttransaction',
            index=models.Index(fields=['transaction_type', '-created_at'], name='core_receip_transac_563d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='receipttransaction',
            index=models.Index(fields=['status', '-created_at'], name='core_receip_status_01afa6_idx'),
        ),
    ]
