# Generated by Django 6.0.4 on 2026-04-11 13:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_paymentreceipt_receipttransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(help_text='Account name/label for your reference', max_length=100)),
                ('bank', models.CharField(choices=[('standard_bank', 'Standard Bank'), ('fnb', 'First National Bank (FNB)'), ('absa', 'Absa Bank'), ('nedbank', 'Nedbank'), ('capitec', 'Capitec Bank'), ('investec', 'Investec'), ('african_bank', 'African Bank'), ('tymebank', 'TymeBank'), ('bidvest_bank', 'Bidvest Bank'), ('discovery_bank', 'Discovery Bank'), ('other', 'Other')], help_text='Select your bank', max_length=20)),
                ('other_bank_name', models.CharField(blank=True, help_text="Specify if 'Other' bank selected", max_length=100)),
                ('account_holder_name', models.CharField(help_text='Full name as it appears on the bank account', max_length=100)),
                ('account_number', models.CharField(help_text='Bank account number (digits only)', max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Account number must contain only digits')])),
                ('branch_code', models.CharField(help_text='6-digit branch code', max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', 'Branch code must be exactly 6 digits')])),
                ('account_type', models.CharField(choices=[('cheque', 'Cheque Account'), ('savings', 'Savings Account'), ('transmission', 'Transmission Account'), ('credit_card', 'Credit Card Account'), ('business', 'Business Account')], default='cheque', max_length=20)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this account has been verified by admin')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this account can be used for payouts')),
                ('is_default', models.BooleanField(default=False, help_text='Default account for payouts')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When this account was verified', null=True)),
                ('verification_notes', models.TextField(blank=True, help_text='Admin notes about verification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(limit_choices_to={'user_type': 'service_provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin who verified this account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider Bank Account',
                'verbose_name_plural': 'Provider Bank Accounts',
                'ordering': ['-is_default', '-created_at'],
                'unique_together': {('provider', 'account_name'), ('provider', 'account_number', 'bank')},
            },
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to be paid out', max_digits=10)),
                ('payout_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('instant_payment', 'Instant Payment'), ('cash_send', 'Cash Send'), ('ewallet', 'E-Wallet')], default='bank_transfer', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin processing notes')),
                ('transaction_reference', models.CharField(blank=True, help_text='Transaction reference number', max_length=100)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(limit_choices_to={'user_type': 'service_provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to=settings.AUTH_USER_MODEL)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='core.providerbankaccount')),
            ],
            options={
                'verbose_name': 'Payout Request',
                'verbose_name_plural': 'Payout Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
