# Generated by Django 6.0.4 on 2026-04-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_provider_bank_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyservicefee',
            name='base_fee',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Base monthly service fee', max_digits=10),
        ),
    ]
