# Generated by Django 6.0.4 on 2026-04-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_fix_monthly_service_fee_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyservicefee',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Total fee for the month', max_digits=10),
        ),
    ]
