# Generated by Django 6.0.4 on 2026-04-11 23:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_fix_monthly_service_fee_total_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkPaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fnb_business_account', models.CharField(help_text='FNB Business Account Number', max_length=50)),
                ('fnb_branch_code', models.CharField(help_text='FNB Branch Code', max_length=10)),
                ('auto_process_threshold', models.PositiveIntegerField(default=10, help_text='Minimum number of payouts to trigger auto-processing')),
                ('processing_fee_ewallet', models.DecimalField(decimal_places=2, default=1.5, help_text='Fee per eWallet transaction', max_digits=6)),
                ('processing_fee_eft', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee per EFT transaction', max_digits=6)),
                ('notify_on_completion', models.BooleanField(default=True)),
                ('notification_email', models.EmailField(blank=True, max_length=254)),
                ('require_dual_approval', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_user', models.ForeignKey(blank=True, help_text='User required for approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Payment Settings',
                'verbose_name_plural': 'Bulk Payment Settings',
            },
        ),
        migrations.CreateModel(
            name='PaymentBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_type', models.CharField(choices=[('ewallet', 'eWallet Bulk Payment'), ('eft', 'EFT Bulk Payment'), ('mixed', 'Mixed Payment Types')], default='mixed', max_length=20)),
                ('payout_count', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('csv_content', models.TextField(help_text='CSV content for bank upload')),
                ('csv_filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('generated', 'CSV Generated'), ('uploaded', 'Uploaded to Bank'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='generated', max_length=20)),
                ('bank_reference', models.CharField(blank=True, help_text='Bank transaction reference', max_length=100)),
                ('error_message', models.TextField(blank=True, help_text='Error details if batch failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL)),
                ('payouts', models.ManyToManyField(related_name='payment_batches', to='core.providerpayout')),
            ],
            options={
                'verbose_name_plural': 'Payment Batches',
                'ordering': ['-created_at'],
            },
        ),
    ]
