# Generated by Django 4.2.7 on 2026-04-06 22:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
# import taggit.managers  # Temporarily disabled


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # ('taggit', '0005_auto_20220424_2025'),  # Temporarily disabled
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('basic_title', models.CharField(max_length=200)),
                ('basic_description', models.TextField()),
                ('basic_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('basic_delivery_days', models.PositiveIntegerField()),
                ('standard_title', models.CharField(blank=True, max_length=200)),
                ('standard_description', models.TextField(blank=True)),
                ('standard_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('standard_delivery_days', models.PositiveIntegerField(blank=True, null=True)),
                ('premium_title', models.CharField(blank=True, max_length=200)),
                ('premium_description', models.TextField(blank=True)),
                ('premium_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('premium_delivery_days', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='gig_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='gig_videos/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('orders_in_queue', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gigs.category')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='gigs.category')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GigRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=200)),
                ('is_required', models.BooleanField(default=True)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='gigs.gig')),
            ],
        ),
        migrations.CreateModel(
            name='GigGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gig_gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='gigs.gig')),
            ],
        ),
        migrations.CreateModel(
            name='GigFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='gigs.gig')),
            ],
        ),
        migrations.AddField(
            model_name='gig',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gigs.subcategory'),
        ),
        # migrations.AddField(
        #     model_name='gig',
        #     name='tags',
        #     field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        # ),
        migrations.CreateModel(
            name='GigPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('delivery_days', models.PositiveIntegerField()),
                ('revisions', models.PositiveIntegerField(default=1)),
                ('features', models.TextField(help_text='One feature per line')),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='gigs.gig')),
            ],
            options={
                'unique_together': {('gig', 'name')},
            },
        ),
    ]
