# Generated by Django 4.2.7 on 2026-04-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_convert_gig_to_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gig',
            options={'ordering': ['-created_at'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterField(
            model_name='gig',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='job_images/'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='urgency',
            field=models.CharField(choices=[('asap', 'ASAP'), ('within_week', 'Within a week'), ('within_month', 'Within a month'), ('flexible', 'Flexible')], default='flexible', max_length=20),
        ),
        migrations.AlterField(
            model_name='gig',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='job_videos/'),
        ),
    ]
