# Generated by Django 4.2.7 on 2026-04-07 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gigs', '0004_gig_hired_provider_gig_is_private_gig_job_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget_range', models.CharField(blank=True, help_text='Optional budget range', max_length=100)),
                ('urgency', models.CharField(choices=[('asap', 'ASAP'), ('within_week', 'Within a week'), ('within_month', 'Within a month'), ('flexible', 'Flexible')], default='flexible', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('receiving_responses', 'Receiving Responses'), ('evaluating', 'Evaluating'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gigs.category')),
                ('homeowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_requests', to=settings.AUTH_USER_MODEL)),
                ('selected_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_breakdown', models.TextField(help_text='Detailed breakdown of costs')),
                ('estimated_duration', models.CharField(help_text='How long the job will take', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments')),
                ('availability', models.TextField(help_text='Provider availability for this job')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('quotation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='gigs.quotationrequest')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['estimated_price'],
                'unique_together': {('quotation_request', 'service_provider')},
            },
        ),
    ]
