# Generated by Django 4.2.7 on 2026-04-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0005_quotationrequest_quotationresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='end_date',
            field=models.DateField(blank=True, help_text='Expected completion date for the job', null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='start_date',
            field=models.DateField(blank=True, help_text='Expected start date for the job', null=True),
        ),
    ]
