# Generated by Django 4.2.7 on 2026-04-07 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gigs', '0006_gig_end_date_gig_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(help_text="Why you're the best fit for this job")),
                ('proposed_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Your proposed rate', max_digits=10, null=True)),
                ('estimated_duration', models.CharField(help_text='How long you estimate the job will take', max_length=100)),
                ('availability_start', models.DateField(blank=True, help_text="When you're available to start", null=True)),
                ('portfolio_links', models.TextField(blank=True, help_text='Links to relevant portfolio items')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='gigs.gig')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('gig', 'service_provider')},
            },
        ),
    ]
