# Generated by Django 6.0.4 on 2026-04-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0007_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='response_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for service providers to submit their quotes', null=True),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('receiving_responses', 'Receiving Responses'), ('evaluation_period', 'Evaluation Period'), ('provider_selected', 'Provider Selected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
