# Generated by Django 4.2.7 on 2026-04-07 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_days',
        ),
        migrations.RemoveField(
            model_name='order',
            name='freelancer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='package',
        ),
        migrations.AddField(
            model_name='order',
            name='homeowner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeowner_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='requirements',
            field=models.TextField(help_text="Homeowner's specific requirements for this order"),
        ),
    ]
