# Generated by Django 6.0.4 on 2026-04-08 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_joboffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_offer', to='orders.order'),
        ),
    ]
