# Generated by Django 6.0.4 on 2026-04-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_joboffer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('in_app', 'In-App Payment'), ('in_person', 'In-Person Payment')], default='in_app', help_text='How the homeowner will pay the service provider', max_length=20),
        ),
    ]
