# Generated by Django 6.0.4 on 2026-04-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ozow_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('payfast', 'PayFast (Online Payment)'), ('yoco', 'Yoco (Card Payment)'), ('ozow', 'Ozow (Instant EFT)'), ('eft', 'EFT Transfer'), ('in_person', 'In-Person Payment')], default='in_app', help_text='How the homeowner will pay the service provider', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
