# Generated by Django 6.0.4 on 2026-04-11 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_ozow_transaction_id_alter_order_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(help_text='e.g., Standard Bank, FNB, Absa', max_length=100)),
                ('branch_code', models.CharField(help_text='6-digit branch code', max_length=10)),
                ('account_holder_name', models.CharField(help_text='Full name of account holder', max_length=100)),
                ('account_number', models.CharField(help_text='Bank account number', max_length=20)),
                ('account_type', models.CharField(choices=[('cheque', 'Cheque Account'), ('savings', 'Savings Account'), ('transmission', 'Transmission Account'), ('credit_card', 'Credit Card Account')], default='cheque', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether these bank details are currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bank Details',
                'verbose_name_plural': 'Bank Details',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('yoco', 'Yoco (Card Payment)'), ('ozow', 'Ozow (Instant EFT)'), ('eft', 'EFT Transfer'), ('in_person', 'In-Person Payment')], default='in_app', help_text='How the homeowner will pay the service provider', max_length=20),
        ),
        migrations.CreateModel(
            name='EFTPaymentConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('proof_of_payment', models.ImageField(blank=True, help_text='Upload proof of payment', null=True, upload_to='eft_proofs/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the payment')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether admin has verified the payment')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eft_confirmation', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_eft_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EFT Payment Confirmation',
                'verbose_name_plural': 'EFT Payment Confirmations',
                'ordering': ['-confirmed_at'],
            },
        ),
    ]
